<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200608173729 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE WAREHOUSES (ID_WAREHOUSE INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, PHONE_NUMBER VARCHAR(10) NOT NULL, EMAIL VARCHAR(200) NOT NULL, ID_MAX_CAPACITY INT DEFAULT NULL, ID_ADRESSE INT DEFAULT NULL, INDEX FK_RESIDE_IN (ID_ADRESSE), INDEX FK_LIMITED_BY (ID_MAX_CAPACITY), PRIMARY KEY(ID_WAREHOUSE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ROLES (ID_ROLE INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, PRIMARY KEY(ID_ROLE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MAINTENANCE_MANUALS (ID_MAINTENANCE_MANUAL INT AUTO_INCREMENT NOT NULL, IMMATRICULATION VARCHAR(20) NOT NULL, MILEAGE INT NOT NULL, GREY_CARD TEXT NOT NULL, INSURANCE VARCHAR(30) NOT NULL, AGE INT NOT NULL, COMMENT TEXT DEFAULT NULL, DATE DATE DEFAULT NULL, ID_TRUCK INT DEFAULT NULL, INDEX FK_HAS_TO_KEEP_UP (ID_TRUCK), PRIMARY KEY(ID_MAINTENANCE_MANUAL)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SUB_CATEGORIES (ID_SUB_CATEGORY INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, DESCRIPTION TEXT DEFAULT NULL, IMAGE TEXT NOT NULL, ID_CATEGORY INT DEFAULT NULL, INDEX FK_SUB_CATEGORIZED_BY (ID_CATEGORY), PRIMARY KEY(ID_SUB_CATEGORY)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE REWARDS (ID_REWARD INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, MINIMAL_POINTS INT NOT NULL, PRIMARY KEY(ID_REWARD)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reward_contents (ID_REWARD INT NOT NULL, ID_MENU INT NOT NULL, INDEX IDX_776DCA4E399E0CD (ID_REWARD), INDEX IDX_776DCA48A1F78F (ID_MENU), PRIMARY KEY(ID_REWARD, ID_MENU)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CITIES (ID_CITY INT AUTO_INCREMENT NOT NULL, POSTAL_NUMBER VARCHAR(5) NOT NULL, NAME VARCHAR(200) NOT NULL, ID_DEPARTMENT INT DEFAULT NULL, INDEX FK_IS_ALSO_SITUATED_IN (ID_DEPARTMENT), PRIMARY KEY(ID_CITY)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE FRANCHISES (ID_FRANCHISE INT AUTO_INCREMENT NOT NULL, EMAIL VARCHAR(200) NOT NULL, FIRST_NAME VARCHAR(50) NOT NULL, LAST_NAME VARCHAR(50) NOT NULL, PASSWORD VARCHAR(100) NOT NULL, PROFILE_PICTURE TEXT DEFAULT NULL, BIRTH_DATE DATE NOT NULL, ID_ADRESSE INT DEFAULT NULL, INDEX FK_LIVE_AT (ID_ADRESSE), UNIQUE INDEX `UNIQUE` (EMAIL), PRIMARY KEY(ID_FRANCHISE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE franchise_stocks (ID_FRANCHISE INT NOT NULL, ID_PRODUCT INT NOT NULL, INDEX IDX_36D26BB23CAC38CD (ID_FRANCHISE), INDEX IDX_36D26BB2FF3ED2B4 (ID_PRODUCT), PRIMARY KEY(ID_FRANCHISE, ID_PRODUCT)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE participates (ID_FRANCHISE INT NOT NULL, ID_EVENT INT NOT NULL, INDEX IDX_330175243CAC38CD (ID_FRANCHISE), INDEX IDX_3301752414B4D2ED (ID_EVENT), PRIMARY KEY(ID_FRANCHISE, ID_EVENT)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE votes (ID_FRANCHISE INT NOT NULL, ID_USER INT NOT NULL, INDEX IDX_518B7ACF3CAC38CD (ID_FRANCHISE), INDEX IDX_518B7ACFF8371B55 (ID_USER), PRIMARY KEY(ID_FRANCHISE, ID_USER)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE EVENTS (ID_EVENT INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, DESCRIPTION TEXT DEFAULT NULL, DATE_BEGIN DATE NOT NULL, DATE_END DATE NOT NULL, PRICE NUMERIC(8, 2) NOT NULL, PRIMARY KEY(ID_EVENT)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE USERS (ID_USER INT AUTO_INCREMENT NOT NULL, PSEUDO VARCHAR(30) NOT NULL, FIRST_NAME VARCHAR(50) NOT NULL, LAST_NAME VARCHAR(50) NOT NULL, EMAIL VARCHAR(200) NOT NULL, PHONE_NUMBER VARCHAR(10) DEFAULT NULL, EURO_POINTS INT DEFAULT NULL, FORMULE_POINTS INT DEFAULT NULL, IS_ACTIVATED TINYINT(1) DEFAULT NULL, PASSWORD VARCHAR(100) NOT NULL, BIRTH_DATE DATE NOT NULL, ID_ROLE INT DEFAULT NULL, INDEX FK_TAKE_PERMISSIONS_FROM (ID_ROLE), UNIQUE INDEX `UNIQUE` (EMAIL), PRIMARY KEY(ID_USER)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE can_claim (ID_USER INT NOT NULL, ID_REWARD INT NOT NULL, INDEX IDX_D8BCAD4AF8371B55 (ID_USER), INDEX IDX_D8BCAD4AE399E0CD (ID_REWARD), PRIMARY KEY(ID_USER, ID_REWARD)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MENU (ID_MENU INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, DESCRIPTION TEXT DEFAULT NULL, IMAGE TEXT NOT NULL, PRICE NUMERIC(8, 2) NOT NULL, VAT NUMERIC(8, 2) NOT NULL, ID_FRANCHISE INT DEFAULT NULL, INDEX FK_OWNS (ID_FRANCHISE), PRIMARY KEY(ID_MENU)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE concerns (ID_MENU INT NOT NULL, ID_USER_ORDER INT NOT NULL, INDEX IDX_C32BFA2A8A1F78F (ID_MENU), INDEX IDX_C32BFA2A151D6013 (ID_USER_ORDER), PRIMARY KEY(ID_MENU, ID_USER_ORDER)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SALE_RECORDS (ID_SALE_RECORD INT AUTO_INCREMENT NOT NULL, DATE DATE DEFAULT NULL, TOTAL_EXPENSES NUMERIC(8, 2) DEFAULT NULL, TOTAL_REVENUES NUMERIC(8, 2) DEFAULT NULL, TOTAL_PROFITS NUMERIC(8, 2) DEFAULT NULL, TOTAL_VAT NUMERIC(8, 2) DEFAULT NULL, ID_FRANCHISE INT DEFAULT NULL, INDEX FK_HAS (ID_FRANCHISE), PRIMARY KEY(ID_SALE_RECORD)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BREAKDOWN_TYPES (ID_BREAKDOWN_TYPE INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, DESCRIPTION TEXT DEFAULT NULL, PRIMARY KEY(ID_BREAKDOWN_TYPE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CREDIT_CARDS (ID_CREDIT_CARD INT AUTO_INCREMENT NOT NULL, CARD_NUMBER VARCHAR(16) NOT NULL, EXPIRATION_DATE DATE NOT NULL, VERIFICATION_CODE VARCHAR(3) NOT NULL, NAME VARCHAR(50) NOT NULL, ID_USER INT DEFAULT NULL, INDEX FK_OWN (ID_USER), PRIMARY KEY(ID_CREDIT_CARD)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TECHNICAL_CONTROLS (ID_TECHNICAL_CONTROL INT AUTO_INCREMENT NOT NULL, DATE DATE NOT NULL, PICTURE TEXT NOT NULL, COMMENT TEXT DEFAULT NULL, ID_TRUCK INT DEFAULT NULL, INDEX FK_CAN_HAVE (ID_TRUCK), PRIMARY KEY(ID_TECHNICAL_CONTROL)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE USER_ORDERS (ID_USER_ORDER INT AUTO_INCREMENT NOT NULL, COMMENT TEXT DEFAULT NULL, DATE DATE NOT NULL, STATUS VARCHAR(50) NOT NULL, BILL TEXT NOT NULL, ID_USER INT DEFAULT NULL, INDEX FK_MAKE_USER_ORDER (ID_USER), PRIMARY KEY(ID_USER_ORDER)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ARTICLES (ID_ARTICLE INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, DESCRIPTION TEXT DEFAULT NULL, IMAGE TEXT NOT NULL, PRICE NUMERIC(8, 2) NOT NULL, VAT NUMERIC(8, 2) NOT NULL, ID_CATEGORY INT DEFAULT NULL, INDEX FK_ALSO_CATEGORIZED_BY (ID_CATEGORY), PRIMARY KEY(ID_ARTICLE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contains (ID_ARTICLE INT NOT NULL, ID_MENU INT NOT NULL, INDEX IDX_8EFA6A7E2E4ED87F (ID_ARTICLE), INDEX IDX_8EFA6A7E8A1F78F (ID_MENU), PRIMARY KEY(ID_ARTICLE, ID_MENU)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE recipes (ID_ARTICLE INT NOT NULL, ID_PRODUCT INT NOT NULL, INDEX IDX_A369E2B52E4ED87F (ID_ARTICLE), INDEX IDX_A369E2B5FF3ED2B4 (ID_PRODUCT), PRIMARY KEY(ID_ARTICLE, ID_PRODUCT)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE DEPARTMENTS (ID_DEPARTMENT INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(200) NOT NULL, PRIMARY KEY(ID_DEPARTMENT)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MAX_CAPACITIES (ID_MAX_CAPACITY INT AUTO_INCREMENT NOT NULL, MAX_INGREDIENTS INT NOT NULL, MAX_DRINKS INT NOT NULL, MAX_DESSERTS INT NOT NULL, MAX_MEALS INT NOT NULL, PRIMARY KEY(ID_MAX_CAPACITY)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PRODUCTS (ID_PRODUCT INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, DESCRIPTION TEXT DEFAULT NULL, IMAGE TEXT NOT NULL, PRICE NUMERIC(8, 2) NOT NULL, STATUS VARCHAR(50) NOT NULL, VAT NUMERIC(8, 2) NOT NULL, EXPIRY_DATE DATE NOT NULL, QUANTITY INT NOT NULL, ID_CATEGORY INT DEFAULT NULL, INDEX FK_CATEGORIZED_BY (ID_CATEGORY), PRIMARY KEY(ID_PRODUCT)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE warehouse_stocks (ID_PRODUCT INT NOT NULL, ID_WAREHOUSE INT NOT NULL, INDEX IDX_B3A34774FF3ED2B4 (ID_PRODUCT), INDEX IDX_B3A34774B6E97D1B (ID_WAREHOUSE), PRIMARY KEY(ID_PRODUCT, ID_WAREHOUSE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BREAKDOWNS (ID_BREAKDOWN INT AUTO_INCREMENT NOT NULL, STATEMENT VARCHAR(100) NOT NULL, ID_BREAKDOWN_TYPE INT DEFAULT NULL, INDEX FK_SORTED_BY (ID_BREAKDOWN_TYPE), PRIMARY KEY(ID_BREAKDOWN)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CATEGORIES (ID_CATEGORY INT AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, DESCRIPTION TEXT DEFAULT NULL, IMAGE TEXT NOT NULL, PRIMARY KEY(ID_CATEGORY)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE TRUCKS (ID_TRUCK INT AUTO_INCREMENT NOT NULL, BRAND VARCHAR(50) NOT NULL, MODEL VARCHAR(50) NOT NULL, STATUS VARCHAR(50) NOT NULL, FACTORY_DATE DATE NOT NULL, ID_MAX_CAPACITY INT DEFAULT NULL, ID_FRANCHISE INT DEFAULT NULL, INDEX FK_POSSESS (ID_FRANCHISE), INDEX FK_IS_ALSO_LIMITED (ID_MAX_CAPACITY), PRIMARY KEY(ID_TRUCK)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE could_have (ID_TRUCK INT NOT NULL, ID_BREAKDOWN INT NOT NULL, INDEX IDX_283A001FE2D62B40 (ID_TRUCK), INDEX IDX_283A001FE9CC6B40 (ID_BREAKDOWN), PRIMARY KEY(ID_TRUCK, ID_BREAKDOWN)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ADDRESSES (ID_ADRESSE INT AUTO_INCREMENT NOT NULL, STREET VARCHAR(100) NOT NULL, NUMBER INT NOT NULL, NUMBER_COMPLEMENT VARCHAR(5) DEFAULT NULL, ID_CITY INT DEFAULT NULL, ID_EVENT INT DEFAULT NULL, INDEX FK_LOCATED_AT (ID_EVENT), INDEX FK_IS_SITUATED_IN (ID_CITY), PRIMARY KEY(ID_ADRESSE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE also_live_at (ID_ADRESSE INT NOT NULL, ID_USER INT NOT NULL, INDEX IDX_D5A79F60EF2BDE0F (ID_ADRESSE), INDEX IDX_D5A79F60F8371B55 (ID_USER), PRIMARY KEY(ID_ADRESSE, ID_USER)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE FRANCHISE_ORDERS (ID_FRANCHISE_ORDER INT AUTO_INCREMENT NOT NULL, COMMENT TEXT DEFAULT NULL, DATE DATE NOT NULL, STATUS VARCHAR(50) NOT NULL, TOTAL_PRICE NUMERIC(8, 2) NOT NULL, BILL TEXT DEFAULT NULL, PURCHASE_FORM TEXT DEFAULT NULL, ID_FRANCHISE INT DEFAULT NULL, ID_WAREHOUSE INT DEFAULT NULL, INDEX FK_SEND_TO (ID_WAREHOUSE), INDEX FK_MAKE_FRANCHISE_ORDER (ID_FRANCHISE), PRIMARY KEY(ID_FRANCHISE_ORDER)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE franchise_order_content (ID_FRANCHISE_ORDER INT NOT NULL, ID_PRODUCT INT NOT NULL, INDEX IDX_4C6CD40C9EAEF9D0 (ID_FRANCHISE_ORDER), INDEX IDX_4C6CD40CFF3ED2B4 (ID_PRODUCT), PRIMARY KEY(ID_FRANCHISE_ORDER, ID_PRODUCT)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE WAREHOUSES ADD CONSTRAINT FK_A476DF88B56E3F20 FOREIGN KEY (ID_MAX_CAPACITY) REFERENCES MAX_CAPACITIES (ID_MAX_CAPACITY)');
        $this->addSql('ALTER TABLE WAREHOUSES ADD CONSTRAINT FK_A476DF88EF2BDE0F FOREIGN KEY (ID_ADRESSE) REFERENCES ADDRESSES (ID_ADRESSE)');
        $this->addSql('ALTER TABLE MAINTENANCE_MANUALS ADD CONSTRAINT FK_2624F6D8E2D62B40 FOREIGN KEY (ID_TRUCK) REFERENCES TRUCKS (ID_TRUCK)');
        $this->addSql('ALTER TABLE SUB_CATEGORIES ADD CONSTRAINT FK_7B8C204F5965E51F FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES (ID_CATEGORY)');
        $this->addSql('ALTER TABLE reward_contents ADD CONSTRAINT FK_776DCA4E399E0CD FOREIGN KEY (ID_REWARD) REFERENCES REWARDS (ID_REWARD)');
        $this->addSql('ALTER TABLE reward_contents ADD CONSTRAINT FK_776DCA48A1F78F FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU)');
        $this->addSql('ALTER TABLE CITIES ADD CONSTRAINT FK_29A576EDC847EC6F FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENTS (ID_DEPARTMENT)');
        $this->addSql('ALTER TABLE FRANCHISES ADD CONSTRAINT FK_CB4CED2CEF2BDE0F FOREIGN KEY (ID_ADRESSE) REFERENCES ADDRESSES (ID_ADRESSE)');
        $this->addSql('ALTER TABLE franchise_stocks ADD CONSTRAINT FK_36D26BB23CAC38CD FOREIGN KEY (ID_FRANCHISE) REFERENCES FRANCHISES (ID_FRANCHISE)');
        $this->addSql('ALTER TABLE franchise_stocks ADD CONSTRAINT FK_36D26BB2FF3ED2B4 FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT)');
        $this->addSql('ALTER TABLE participates ADD CONSTRAINT FK_330175243CAC38CD FOREIGN KEY (ID_FRANCHISE) REFERENCES FRANCHISES (ID_FRANCHISE)');
        $this->addSql('ALTER TABLE participates ADD CONSTRAINT FK_3301752414B4D2ED FOREIGN KEY (ID_EVENT) REFERENCES EVENTS (ID_EVENT)');
        $this->addSql('ALTER TABLE votes ADD CONSTRAINT FK_518B7ACF3CAC38CD FOREIGN KEY (ID_FRANCHISE) REFERENCES FRANCHISES (ID_FRANCHISE)');
        $this->addSql('ALTER TABLE votes ADD CONSTRAINT FK_518B7ACFF8371B55 FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)');
        $this->addSql('ALTER TABLE USERS ADD CONSTRAINT FK_E3D7675922CD4776 FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE)');
        $this->addSql('ALTER TABLE can_claim ADD CONSTRAINT FK_D8BCAD4AF8371B55 FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)');
        $this->addSql('ALTER TABLE can_claim ADD CONSTRAINT FK_D8BCAD4AE399E0CD FOREIGN KEY (ID_REWARD) REFERENCES REWARDS (ID_REWARD)');
        $this->addSql('ALTER TABLE MENU ADD CONSTRAINT FK_4B90D7273CAC38CD FOREIGN KEY (ID_FRANCHISE) REFERENCES FRANCHISES (ID_FRANCHISE)');
        $this->addSql('ALTER TABLE concerns ADD CONSTRAINT FK_C32BFA2A8A1F78F FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU)');
        $this->addSql('ALTER TABLE concerns ADD CONSTRAINT FK_C32BFA2A151D6013 FOREIGN KEY (ID_USER_ORDER) REFERENCES USER_ORDERS (ID_USER_ORDER)');
        $this->addSql('ALTER TABLE SALE_RECORDS ADD CONSTRAINT FK_85C7B1923CAC38CD FOREIGN KEY (ID_FRANCHISE) REFERENCES FRANCHISES (ID_FRANCHISE)');
        $this->addSql('ALTER TABLE CREDIT_CARDS ADD CONSTRAINT FK_CE339A75F8371B55 FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)');
        $this->addSql('ALTER TABLE TECHNICAL_CONTROLS ADD CONSTRAINT FK_C3217437E2D62B40 FOREIGN KEY (ID_TRUCK) REFERENCES TRUCKS (ID_TRUCK)');
        $this->addSql('ALTER TABLE USER_ORDERS ADD CONSTRAINT FK_C2C34DA7F8371B55 FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)');
        $this->addSql('ALTER TABLE ARTICLES ADD CONSTRAINT FK_79EEAD245965E51F FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES (ID_CATEGORY)');
        $this->addSql('ALTER TABLE contains ADD CONSTRAINT FK_8EFA6A7E2E4ED87F FOREIGN KEY (ID_ARTICLE) REFERENCES ARTICLES (ID_ARTICLE)');
        $this->addSql('ALTER TABLE contains ADD CONSTRAINT FK_8EFA6A7E8A1F78F FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU)');
        $this->addSql('ALTER TABLE recipes ADD CONSTRAINT FK_A369E2B52E4ED87F FOREIGN KEY (ID_ARTICLE) REFERENCES ARTICLES (ID_ARTICLE)');
        $this->addSql('ALTER TABLE recipes ADD CONSTRAINT FK_A369E2B5FF3ED2B4 FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT)');
        $this->addSql('ALTER TABLE PRODUCTS ADD CONSTRAINT FK_7589C6165965E51F FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES (ID_CATEGORY)');
        $this->addSql('ALTER TABLE warehouse_stocks ADD CONSTRAINT FK_B3A34774FF3ED2B4 FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT)');
        $this->addSql('ALTER TABLE warehouse_stocks ADD CONSTRAINT FK_B3A34774B6E97D1B FOREIGN KEY (ID_WAREHOUSE) REFERENCES WAREHOUSES (ID_WAREHOUSE)');
        $this->addSql('ALTER TABLE BREAKDOWNS ADD CONSTRAINT FK_589072E244B3C54C FOREIGN KEY (ID_BREAKDOWN_TYPE) REFERENCES BREAKDOWN_TYPES (ID_BREAKDOWN_TYPE)');
        $this->addSql('ALTER TABLE TRUCKS ADD CONSTRAINT FK_BEE2D60B56E3F20 FOREIGN KEY (ID_MAX_CAPACITY) REFERENCES MAX_CAPACITIES (ID_MAX_CAPACITY)');
        $this->addSql('ALTER TABLE TRUCKS ADD CONSTRAINT FK_BEE2D603CAC38CD FOREIGN KEY (ID_FRANCHISE) REFERENCES FRANCHISES (ID_FRANCHISE)');
        $this->addSql('ALTER TABLE could_have ADD CONSTRAINT FK_283A001FE2D62B40 FOREIGN KEY (ID_TRUCK) REFERENCES TRUCKS (ID_TRUCK)');
        $this->addSql('ALTER TABLE could_have ADD CONSTRAINT FK_283A001FE9CC6B40 FOREIGN KEY (ID_BREAKDOWN) REFERENCES BREAKDOWNS (ID_BREAKDOWN)');
        $this->addSql('ALTER TABLE ADDRESSES ADD CONSTRAINT FK_2B086BF958FFCF28 FOREIGN KEY (ID_CITY) REFERENCES CITIES (ID_CITY)');
        $this->addSql('ALTER TABLE ADDRESSES ADD CONSTRAINT FK_2B086BF914B4D2ED FOREIGN KEY (ID_EVENT) REFERENCES EVENTS (ID_EVENT)');
        $this->addSql('ALTER TABLE also_live_at ADD CONSTRAINT FK_D5A79F60EF2BDE0F FOREIGN KEY (ID_ADRESSE) REFERENCES ADDRESSES (ID_ADRESSE)');
        $this->addSql('ALTER TABLE also_live_at ADD CONSTRAINT FK_D5A79F60F8371B55 FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER)');
        $this->addSql('ALTER TABLE FRANCHISE_ORDERS ADD CONSTRAINT FK_3E65081B3CAC38CD FOREIGN KEY (ID_FRANCHISE) REFERENCES FRANCHISES (ID_FRANCHISE)');
        $this->addSql('ALTER TABLE FRANCHISE_ORDERS ADD CONSTRAINT FK_3E65081BB6E97D1B FOREIGN KEY (ID_WAREHOUSE) REFERENCES WAREHOUSES (ID_WAREHOUSE)');
        $this->addSql('ALTER TABLE franchise_order_content ADD CONSTRAINT FK_4C6CD40C9EAEF9D0 FOREIGN KEY (ID_FRANCHISE_ORDER) REFERENCES FRANCHISE_ORDERS (ID_FRANCHISE_ORDER)');
        $this->addSql('ALTER TABLE franchise_order_content ADD CONSTRAINT FK_4C6CD40CFF3ED2B4 FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE warehouse_stocks DROP FOREIGN KEY FK_B3A34774B6E97D1B');
        $this->addSql('ALTER TABLE FRANCHISE_ORDERS DROP FOREIGN KEY FK_3E65081BB6E97D1B');
        $this->addSql('ALTER TABLE USERS DROP FOREIGN KEY FK_E3D7675922CD4776');
        $this->addSql('ALTER TABLE reward_contents DROP FOREIGN KEY FK_776DCA4E399E0CD');
        $this->addSql('ALTER TABLE can_claim DROP FOREIGN KEY FK_D8BCAD4AE399E0CD');
        $this->addSql('ALTER TABLE ADDRESSES DROP FOREIGN KEY FK_2B086BF958FFCF28');
        $this->addSql('ALTER TABLE franchise_stocks DROP FOREIGN KEY FK_36D26BB23CAC38CD');
        $this->addSql('ALTER TABLE participates DROP FOREIGN KEY FK_330175243CAC38CD');
        $this->addSql('ALTER TABLE votes DROP FOREIGN KEY FK_518B7ACF3CAC38CD');
        $this->addSql('ALTER TABLE MENU DROP FOREIGN KEY FK_4B90D7273CAC38CD');
        $this->addSql('ALTER TABLE SALE_RECORDS DROP FOREIGN KEY FK_85C7B1923CAC38CD');
        $this->addSql('ALTER TABLE TRUCKS DROP FOREIGN KEY FK_BEE2D603CAC38CD');
        $this->addSql('ALTER TABLE FRANCHISE_ORDERS DROP FOREIGN KEY FK_3E65081B3CAC38CD');
        $this->addSql('ALTER TABLE participates DROP FOREIGN KEY FK_3301752414B4D2ED');
        $this->addSql('ALTER TABLE ADDRESSES DROP FOREIGN KEY FK_2B086BF914B4D2ED');
        $this->addSql('ALTER TABLE votes DROP FOREIGN KEY FK_518B7ACFF8371B55');
        $this->addSql('ALTER TABLE can_claim DROP FOREIGN KEY FK_D8BCAD4AF8371B55');
        $this->addSql('ALTER TABLE CREDIT_CARDS DROP FOREIGN KEY FK_CE339A75F8371B55');
        $this->addSql('ALTER TABLE USER_ORDERS DROP FOREIGN KEY FK_C2C34DA7F8371B55');
        $this->addSql('ALTER TABLE also_live_at DROP FOREIGN KEY FK_D5A79F60F8371B55');
        $this->addSql('ALTER TABLE reward_contents DROP FOREIGN KEY FK_776DCA48A1F78F');
        $this->addSql('ALTER TABLE concerns DROP FOREIGN KEY FK_C32BFA2A8A1F78F');
        $this->addSql('ALTER TABLE contains DROP FOREIGN KEY FK_8EFA6A7E8A1F78F');
        $this->addSql('ALTER TABLE BREAKDOWNS DROP FOREIGN KEY FK_589072E244B3C54C');
        $this->addSql('ALTER TABLE concerns DROP FOREIGN KEY FK_C32BFA2A151D6013');
        $this->addSql('ALTER TABLE contains DROP FOREIGN KEY FK_8EFA6A7E2E4ED87F');
        $this->addSql('ALTER TABLE recipes DROP FOREIGN KEY FK_A369E2B52E4ED87F');
        $this->addSql('ALTER TABLE CITIES DROP FOREIGN KEY FK_29A576EDC847EC6F');
        $this->addSql('ALTER TABLE WAREHOUSES DROP FOREIGN KEY FK_A476DF88B56E3F20');
        $this->addSql('ALTER TABLE TRUCKS DROP FOREIGN KEY FK_BEE2D60B56E3F20');
        $this->addSql('ALTER TABLE franchise_stocks DROP FOREIGN KEY FK_36D26BB2FF3ED2B4');
        $this->addSql('ALTER TABLE recipes DROP FOREIGN KEY FK_A369E2B5FF3ED2B4');
        $this->addSql('ALTER TABLE warehouse_stocks DROP FOREIGN KEY FK_B3A34774FF3ED2B4');
        $this->addSql('ALTER TABLE franchise_order_content DROP FOREIGN KEY FK_4C6CD40CFF3ED2B4');
        $this->addSql('ALTER TABLE could_have DROP FOREIGN KEY FK_283A001FE9CC6B40');
        $this->addSql('ALTER TABLE SUB_CATEGORIES DROP FOREIGN KEY FK_7B8C204F5965E51F');
        $this->addSql('ALTER TABLE ARTICLES DROP FOREIGN KEY FK_79EEAD245965E51F');
        $this->addSql('ALTER TABLE PRODUCTS DROP FOREIGN KEY FK_7589C6165965E51F');
        $this->addSql('ALTER TABLE MAINTENANCE_MANUALS DROP FOREIGN KEY FK_2624F6D8E2D62B40');
        $this->addSql('ALTER TABLE TECHNICAL_CONTROLS DROP FOREIGN KEY FK_C3217437E2D62B40');
        $this->addSql('ALTER TABLE could_have DROP FOREIGN KEY FK_283A001FE2D62B40');
        $this->addSql('ALTER TABLE WAREHOUSES DROP FOREIGN KEY FK_A476DF88EF2BDE0F');
        $this->addSql('ALTER TABLE FRANCHISES DROP FOREIGN KEY FK_CB4CED2CEF2BDE0F');
        $this->addSql('ALTER TABLE also_live_at DROP FOREIGN KEY FK_D5A79F60EF2BDE0F');
        $this->addSql('ALTER TABLE franchise_order_content DROP FOREIGN KEY FK_4C6CD40C9EAEF9D0');
        $this->addSql('DROP TABLE WAREHOUSES');
        $this->addSql('DROP TABLE ROLES');
        $this->addSql('DROP TABLE MAINTENANCE_MANUALS');
        $this->addSql('DROP TABLE SUB_CATEGORIES');
        $this->addSql('DROP TABLE REWARDS');
        $this->addSql('DROP TABLE reward_contents');
        $this->addSql('DROP TABLE CITIES');
        $this->addSql('DROP TABLE FRANCHISES');
        $this->addSql('DROP TABLE franchise_stocks');
        $this->addSql('DROP TABLE participates');
        $this->addSql('DROP TABLE votes');
        $this->addSql('DROP TABLE EVENTS');
        $this->addSql('DROP TABLE USERS');
        $this->addSql('DROP TABLE can_claim');
        $this->addSql('DROP TABLE MENU');
        $this->addSql('DROP TABLE concerns');
        $this->addSql('DROP TABLE SALE_RECORDS');
        $this->addSql('DROP TABLE BREAKDOWN_TYPES');
        $this->addSql('DROP TABLE CREDIT_CARDS');
        $this->addSql('DROP TABLE TECHNICAL_CONTROLS');
        $this->addSql('DROP TABLE USER_ORDERS');
        $this->addSql('DROP TABLE ARTICLES');
        $this->addSql('DROP TABLE contains');
        $this->addSql('DROP TABLE recipes');
        $this->addSql('DROP TABLE DEPARTMENTS');
        $this->addSql('DROP TABLE MAX_CAPACITIES');
        $this->addSql('DROP TABLE PRODUCTS');
        $this->addSql('DROP TABLE warehouse_stocks');
        $this->addSql('DROP TABLE BREAKDOWNS');
        $this->addSql('DROP TABLE CATEGORIES');
        $this->addSql('DROP TABLE TRUCKS');
        $this->addSql('DROP TABLE could_have');
        $this->addSql('DROP TABLE ADDRESSES');
        $this->addSql('DROP TABLE also_live_at');
        $this->addSql('DROP TABLE FRANCHISE_ORDERS');
        $this->addSql('DROP TABLE franchise_order_content');
    }
}
