easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Role
        - App\Entity\User
        - App\Entity\Franchise
        - App\Entity\Truck
        - App\Entity\Warehouse
        - App\Entity\Address
        - App\Entity\City
        - App\Entity\Department
        - App\Entity\MaxCapacity
        - App\Entity\SubCategory
        - App\Entity\Category
        - App\Entity\Product
        - App\Entity\FranchiseOrder

