# Configuration de Enzo et Alex. Ne pas supprimer svp. Commentez si besoin.

#doctrine_migrations:
#    dir_name: '%kernel.project_dir%/src/Migrations'
#    namespace: DoctrineMigrations
    # migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
    #    'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'


# Configuration de Romain. Ne pas supprimer svp. Commentez si besoin.

doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'

        
