vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:

        categorie_images:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        sub_categorie_images:
            uri_prefix: /images/sub-categories
            upload_destination: '%kernel.project_dir%/public/images/sub-categories'
            inject_on_load:     true
            delete_on_update:  true
            delete_on_remove:   true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        product_images:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        article_images:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        event_images:
            uri_prefix: /images/event
            upload_destination: '%kernel.project_dir%/public/images/event'
            inject_on_load:     true
            delete_on_update:   false
            delete_on_remove:   false
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        profile_images:
            uri_prefix: /images/profile
            upload_destination: '%kernel.project_dir%/public/images/profile'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        maintenance_images:
            uri_prefix: /images/maintenance
            upload_destination: '%kernel.project_dir%/public/images/maintenance'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer







